Display wordlists
UMM-CSci-3601-S21/it-1-purple-tigers pull request #4
Opened 2021-03-07 17:08 UTC by schu4276

This adds the code base for displaying existing wordlists, and a start on the addition of new wordlists.

2021-03-08 21:44 UTC, dahlgrenthomas approved these changes, later dismissed
Looks awesome

2021-03-08 23:53 UTC, NicMcPhee requested changes
I didn't do a full review (this is a _huge_ PR, which means no one is probably doing a really careful review), but I did copy over the more serious of the three LGTM warnings. You really do need to address that before you merge this in.

2021-03-08 23:53 UTC, NicMcPhee commented on server/src/main/java/umm3601/contextpack/ContextPackController.java
> +      .check(list -> list.topic.matches("^[a-zA-Z]+$") && list.topic != null)
[As LGTM is telling you](https://lgtm.com/projects/g/UMM-CSci-3601-S21/it-1-purple-tigers/snapshot/a6e85d3f22a65fc5191cd64ca504a6a86184f993/files/server/src/main/java/umm3601/contextpack/ContextPackController.java?sort=name&dir=ASC&mode=heatmap), the order of the tests here is wrong in a meaningful way. You only check for `list.top != null` _after_ you've used it in `list.topic.matches`. That means that if it is `null` you'll get a `NullPointerException` when that guard should have ensured that didn't happen.

2021-03-09 19:05 UTC, schu4276 commented
Messy pull request, we are going to reorganize and redo

2021-03-09 19:22 UTC, NicMcPhee approved these changes
Thanks for fixing that.

2021-03-09 19:26 UTC, merged